local-phone-apps = AndroidTerm \
                   ApplicationsProvider \
                   BackupRestoreConfirmation \
                   BasicDreams \
                   Bluetooth \
                   Browser \
                   Calculator \
                   Calendar \
                   CalendarProvider \
                   CellBroadcastReceiver \
                   CertInstaller \
                   Contacts \
                   ContactsProvider \
                   DefaultContainerService \
                   DeskClock \
                   Development \
                   DownloadProvider \
                   DownloadProviderUi \
                   DrmProvider \
                   Email2 \
                   EVToolbox \
                   Exchange2 \
                   FusedLocation \
                   Galaxy4 \
                   Gallery2 \
                   GooglePinyinIME \
                   HoloSpiralWallpaper \
                   HTMLViewer \
                   InputDevices \
                   KeyChain \
                   LatinIME \
                   Launcher2 \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   MagicSmokeWallpapers \
                   MediaProvider \
                   Mms \
                   Music \
                   MusicFX \
                   NoiseField \
                   PackageInstaller \
                   PhaseBeam \
                   Phone \
                   PhotoTable \
                   PicoTts \
                   Provision \
                   QuickSearchBox \
                   RootExplorer \
                   Settings \
                   SettingsProvider \
                   SharedStorageBackup \
                   SoundRecorder \
                   SpeechRecorder \
                   Stk \
                   Superuser \
                   Sweep2Wake \
                   SystemUI \
                   TelephonyProvider \
                   ThemeChooser \
                   ThemeManager \
                   Torch \
                   UserDictionaryProvider \
                   VideoEditor \
                   VisualizationWallpapers \
                   VoiceDialer \
                   VpnDialogs \
                   WAPPushManager \
