local-phone-apps = ApplicationsProvider \
                   BackupRestoreConfirmation \
                   BasicDreams \
                   Bluetooth \
                   CellBroadcastReceiver \
                   CertInstaller \
                   DefaultContainerService \
                   DrmProvider \
                   Galaxy4 \
                   GooglePinyinIME \
                   HoloSpiralWallpaper \
                   HTMLViewer \
                   InputDevices \
                   KeyChain \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   MagicSmokeWallpapers \
                   MediaProvider \
                   NoiseField \
                   PhaseBeam \
                   PhotoTable \
                   PicoTts \
                   RootExplorer \
                   SharedStorageBackup \
                   Sweep2Wake \
                   Stk \
                   UserDictionaryProvider \
                   VisualizationWallpapers \
                   WAPPushManager
